### ISSUE TITLE
Wrong formating in details file...

### ISSUE THREAD

**Issue by rantanlan** [asifbacchus/MailcowBackup#11]
You made the follwing changes to the details file, but the script is complaining afterwards regarding the spaces!?
Otherwise thanks for the additons 👍 

```
-borgSSHKey="/var/borgbackup/private.key"
+borgSSHKey = "/var/borgbackup/private.key"
-borgBaseDir="/var/borgbackup"
+borgBaseDir = "/var/borgbackup"
-borgConnectRepo="jdoe123@borg.server.net:mailcow/"
+borgConnectRepo = "jdoe123@borg.server.net:mailcow/"
```
```
/var/borgbackup/backup.sh: 19: /var/borgbackup/backup.details: borgSSHPort: not found
/var/borgbackup/backup.sh: 24: /var/borgbackup/backup.details: borgBaseDir: not found
/var/borgbackup/backup.sh: 33: /var/borgbackup/backup.details: borgConnectRep: not found
```

**Comment by asifbacchus** [comment]
Ahhhh! Yup, using a new IDE and it auto-formatted the file to insert spaces! Thanks for pointing that out.

Corrected with above commit and in a new point release -- [Version 3.5.1](https://github.com/asifbacchus/MailcowBackup/releases/tag/MailcowBackupV3.5.1)
