### ISSUE TITLE
[Suggestion] add version of script in help 

### ISSUE THREAD

**Issue by bengivre** [asifbacchus/MailcowBackup#12]
Hi , 
It would be nice to have a way to know the actual version of the script ;) 
I did not found it, so I am not sure if it is already somewhere. 

Thanks for you contribution on that backup script. 

Ben

**Comment by asifbacchus** [comment]
Haha, probably not a bad idea! I think I'll implement it along with an auto-update... probably get to it this weekend.

Oh, and thanks for the kind words :-)

**Comment by asifbacchus** [comment]
sorry, meant to update this earlier -- resolved with 47adaceed0f8e6e325da27903d0919c9ab9f5f5e
