### ISSUE TITLE
backup script not working with docker compose v2

### ISSUE THREAD

**Issue by ckruijntjens** [asifbacchus/MailcowBackup#13]
Hi,

the script is not working anymore with docker compose v2 (latest mailcow and docker update)

error is:

Return low-level information on Docker objects
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

**Comment by ckruijntjens** [comment]
this was false. errors where because of a qouta setting.

**Comment by asifbacchus** [comment]
Glad you figured it out :-) Was the quota issue something to do with the script or with your particular set-up? Just curious.

**Comment by ckruijntjens** [comment]
> Glad you figured it out :-) Was the quota issue something to do with the script or with your particular set-up? Just curious.

Hi,

With my setup. I use a btrfs filesystem with quota enabled. If it reaches the threshold it becomes a read only filesystem.
