### ISSUE TITLE
same issue as in #13

### ISSUE THREAD

**Issue by rantanlan** [asifbacchus/MailcowBackup#14]
Hey

I just found out my backup stopped working too with the same issue as in #13 
Can't figure out why. Maybe a syntax change in docker itself with the new compose v2?

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Any idea on this one? Didn't change anything besides upgrading to compose v2 as suggested and don't use btrfs

**Comment by asifbacchus** [comment]
Hmmm... seems I updated forgot to push the latest updates from my private repo to this public one here. I think the newest version of the script should resolve any issues you are having. I use it daily with compose v2 and don't have any issues.

If problems persist, would you mind attaching/sending me a copy of your most recent log? That way maybe I can isolate the issue. 

Thanks and sorry you're running into issues!

**Comment by rantanlan** [comment]
thanks a lot, working fine again :)

**Comment by asifbacchus** [comment]
Glad it all got sorted out. I'll be more attentive when publishing updates in the future to avoid this confusion!

Cheers. Closing issue.
