### ISSUE TITLE
Reports can't start Dovecot/Postfix 

### ISSUE THREAD

**Issue by Ry3nlNaToR** [asifbacchus/MailcowBackup#3]
Hi the script seem to be reporting it couldn't start Dovecot and Postfix when it dose manage to start it.

Got this from logs 

[ERROR] Could not start Postfix container. Please check docker logs (code: 103)
[ERROR] Could not start Dovecot container. Please check docker logs (code: 104)
docker inspect" requires at least 1 argument.

**Comment by asifbacchus** [comment]
Anything in your docker logs? Are the containers stopped? Can you start them manually without errors?

You can check logs with

```bash
docker logs containername
```

And you can manually start them with

```bash
cd /your/mailcow/directory
docker-compose start containername
```

Has the script run in the past or is this the first time you are running it?  Also, have you manually named your containers or are you using the defaults?

Finally, could you please give me the **exact** command you are using to invoke the script?

**Comment by Ry3nlNaToR** [comment]
The first time I've used this script to backup the script dose manage to stop and start the containers it just returns a false error saying it couldn't since the output is also mentioning docker inspect" requires at least 1 argument. 

The issue is probably  caused by this line https://github.com/asifbacchus/MailcowBackup/blob/a26bb36f176f55dd72c7df63d0dfddcb928ae24d/root/scripts/backup.sh#L245 that check if the container is running.

The command I used to run is  /root/backup/backup.sh -m "/root/mailcow/mailcow.conf"  all the containers are the default name.

The script dose manage backup and start and stop everything I could just add >/dev/null 2>&1 to cronjob line to hide the output.

**Comment by asifbacchus** [comment]
First of all, I would **always** run a cronjob with `> /dev/null 2>&1` regardless, good call on that.

Give me a day to spin up the latest mailcow on a test server and have a look. I haven't updated in a few months so maybe something has changed in how the containers are named or something and that is causing the script to generate false errors.

Out of interest, if you run the script normally as root at the console do you get any errors? If you are only getting errors when running as a cronjob I have a whole different idea of why that could be happening -- let me know?

I'm glad it's at least getting your backups done! Thx for letting me know about this issue.

**Comment by asifbacchus** [comment]
Just an update -- I managed to duplicate the error you are finding and it is indeed only on newer versions of mailcow.  I'll track the issue down, just wanted to give you a heads up, haven't forgotten about you, @Ry3nlNaToR  :-)

**Comment by asifbacchus** [comment]
Ok, I was wrong, it was actually just a sloppy mistake I never noticed before. I was checking names of only running containers and, obviously, postfix and dovecot would *not* be running after they were stopped!  Should be resolved now.

commit: 04bc748

**Comment by asifbacchus** [comment]
New minor release [Version 1.5.1](https://github.com/asifbacchus/MailcowBackup/releases/tag/MailcowBackupV1.5.1) includes this fix. Just noting for anyone that finds this issue.

@Ry3nlNaToR please confirm this fixes your issue and I'll close this.  Thanks again!

**Comment by Ry3nlNaToR** [comment]
Just tested error now gone.

Thanks.
