### ISSUE TITLE
Wiki is down?

### ISSUE THREAD

**Issue by shaneonabike** [asifbacchus/MailcowBackup#5]
Hey

For some reason I can't access any of the links to your wiki? Is there some issue with your server or is there another instance of your wiki that I could check out.

Thanks for building such a rad tool!

**Comment by asifbacchus** [comment]
Ahhhrghh! I've been having some problems with my hosting provider. Should be up and running in a few minutes. Sorry about that! Thanks for the kind words, btw!

In the meantime, perhaps anything I can help with?

**Comment by shaneonabike** [comment]
It's ok I finally answer my question with one of the configurations variables. I am curious why you didn't set any level of compression on your backups as that would have used less space?

Like --compression lzma, 5 or something

**Comment by asifbacchus** [comment]
Glad you got that sorted out!

To answer your question, if my memory serves, borg does do compression automatically though not anything extensive. I have tons of storage so it wasn't a priority for me versus speed. However, I'd be happy to add an option, if you think it would be a good improvement?

**Comment by shaneonabike** [comment]
Possibly yeah that could be cool. I was able to modify the main borg line to modify teh compression so that's ok too. Thanks for making this great tool!

**Comment by asifbacchus** [comment]
Wow, time got away from me on this one and I kinda forgot. I'll try to add an option this weekend and credit you in the wiki on how to use it 😄

**Comment by asifbacchus** [comment]
Updated the backup script to add a `--compression` parameter that accepts anything borg accepts. Thanks for the suggestion! It's in the version 3.0 release.

**Comment by asifbacchus** [comment]
closed with 85e34c73a3e02057319580eeed448967e5f9c442

**Comment by pcace** [comment]
> closed with [85e34c7](https://github.com/asifbacchus/MailcowBackup/commit/85e34c73a3e02057319580eeed448967e5f9c442)

just found it here in the closed issues.. could be added to the documentation - it would make searching easier ;) 
thanks anyways for that great script!
