### ISSUE TITLE
Feature ideas and / or requests - Colours in log and SSH port config

### ISSUE THREAD

**Issue by rantanlan** [asifbacchus/MailcowBackup#9]
Hey,

just finished my mailserver and was looking for a backup solution. Found your script and I'm happy with it.

Two things tho, maybe you can make the use of colour in the logfile optional? It would make parsing and looking at it with different tools more easily. (I just removed the command -v tput...)

Also, my remote server is not listening to the default ssh port 22 due to secrity reasons, so I modified line 512 to use a different port. 

`export BORG_RSH="ssh -p 0815 -i ${borgSSHKey}"`

Would be nice to have this as a configuration option also

Otherwise thanks for your script.

**Comment by asifbacchus** [comment]
Glad it's working out for you! I've actually been thinking about those exact suggestions for a little while now and was going to put them into the next version. Here are my thoughts at the moment:

- command-line switch to disable logfile colouring
- SSH-port in the configuration details file

I should be able to make the changes this weekend, I'll keep you posted. Thanks for the suggestions! I very much appreciate it.

**Comment by asifbacchus** [comment]
Implemented as noted above with commits.
Both suggestions implemented in [Version 3.5](https://github.com/asifbacchus/MailcowBackup/releases/tag/MailcowBackupV3.5)

Feel free to re-open if I missed something. Thanks again for the great suggestions!
